css/style.css, index.html
- fixed a typo in footer
- added padding to footer discord button
=> Fixing some typos in footer

css/style.css, index.html, js/script.js
#12 issue solved . @Zack-Dx please review the pr and merge
=> added scroll up button

css/style.css, index.html
Make the cursor pointer when hover these icon and select tag.
=> feat: add cursor pointer to footer icon

css/style.css, index.html
Increase UX of the Discord clone by adding **external social media icons** and its links in the _footer_ and also, **added cursor** property in the _country id._
=> added social media links in footer instead of pic

css/style.css, index.html, js/script.js
=> Added Dark Mode Toogle

index.html
- Aligned the Text using break statement in HTML.
- Match the Text with Discord original website and add into it.
Thanks!!
=> Aligned the Text as like Discord Website using break statemnts

css/style.css, index.html
Make changes to the footer styles the same as the original website
Before:
Original:
After:
=> Small changes footer styles

css/responsive.css, css/style.css, index.html, js/script.js
- Modified the HTML  file a little to some changes required for the mobile menu e.g hamburger icon
- Modified the CSS to style the mobile navbar and made it responsive.
- Mobile menu has been sorted out
=> made the navbar responsive

css/responsive.css, css/style.css
=> made dark toggle responsive

index.html
Change the header of main page from Discord clone to Discord | Your Place to Talk and Hang Out
=> change document header

index.html
Signed-off-by: Srihari S <sshsrn@gmail.com>
=> Light mode Dark mode toggle bug fix

css/style.css
Fix the bug container5 bg colour
=> change container5 background colour

css/style.css, img/stars1.svg, index.html
I have made a few updates to add the following SVG design to the discord clone.
=> Fix Discord Clone Missing Star Design

css/style.css
=> container5 dark mode bug solved

download.html
This PR resolves #159 
I have added the animation on the download page . So when the user scrolls down, the elements on the screen fades up.
=> Added animation

css/style.css, index.html
Fixed login button and hover effect on button , 
i am participating in Hacktoberfest approve this PR with a Hacktoberfest tag .
and Happy hacking.
=> fixed login button and hover effect.

css/responsive.css, css/style.css, download.html, index.html
changes were made in html and css , and was able to enhance the css and , user experience of the nav/ ham section for mobile viewport.
i am participating in Hacktoberfest so approve this PR and merge it with Hacktoberfest2022 tag , thanks 
HappyHacking
=> enhanced Ham menu UI and Functioning made it responsive.

css/style.css, css/support.css, index.html
The hover effect in the navbar is improved. Also, edited the night mode feature with specific changes in CSS. This time PR has zero code conflicts.
=> deleted unnecessary CSS code and improved nav li with hover effect 

css/style.css, css/support.css, index.html
Reverts Zack-Dx/Discord-clone-project#181
=> Revert "deleted unnecessary CSS code and improved nav li with hover effect "

index.html
about what you are fixes
Fixes #51 
Type of change
Add hover effect on button and fixing the discord download button.
How should this be tested?
1. Go on home page
2. Scroll down and see another button for download
=> Add#51 - Add of link and hovering effect.
